2019-12-08 21:51:58,477 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 21:54:14,010 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 22:08:12,749 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 22:19:06,679 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 22:19:15,622 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 22:53:47,883 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 22:53:56,773 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 23:10:21,587 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 23:32:46,271 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 23:36:33,076 INFO: BlogEngine startup [in /Users/cartervanekeren/dev/blogengine/app/__init__.py:45
2019-12-08 23:39:19,401 ERROR: Exception on /index [POST] [in /Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cartervanekeren/dev/blogengine/app/routes.py", line 21, in index
    post = Post(body=form.post.data, author=current_user.user)
  File "/Users/cartervanekeren/Environments/flaskenv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'user'
